baseURL: ""
languageCode: en-us
title: Hack docs
menu:
  main:
    - name: home
      url: /
      weight: 1
    - name: categories
      url: "categories/"
      weight: 2
    - name: tags
      url: "tags/"
      weight: 3

params:
  description: "Hack docs"

markup:
  highlight:
    codeFences: true
    style: bw
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
