baseURL: ""
languageCode: en-us
title: Hack docs
menu:
  main:
    - name: "Домой"
      url: /
      weight: 1
    - name: Документация к API
      url: "api/"
      weight: 2

params:
  description: "Hack docs"

markup:
  highlight:
    codeFences: true
    style: bw
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/barklan/hugo-dead-simple
